import Head from "next/head";
import Header from "../components/Header";
import Contracts from "../components/Contracts/Contracts";
import { useAccount } from "wagmi";
import NotConnectedMessage from "@/components/NotConnectedMessage";

export default function Home() {
  const { isConnected } = useAccount();

  const render = () => {
    if (isConnected) {
      return <Contracts />;
    } else {
      return <NotConnectedMessage />;
    }
  };

  return (
    <>
      <Head>
        <title>Escrow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{render()}</main>
    </>
  );
}
